---
title: "FORS 505"
author: "Colin Kirkmire"
date: "April 28, 2016"
output: word_document
---

(4) Compute a 90% CI for the number of TPHA on the whole tract
```{r setup, include=FALSE}

A_1<-c(10.3,10.3,11.2,13.6)
A_2<-c(11.2,8.5,9.4,6.8)
A_3<-c(0)
A_4<-c(9.8,8.9,12.2,5.6,3.4)

B_1<-c(18.9,14.5,12.9,14.2,9.9)
B_2<-c(11.2,21.3,14.2,15.3,8.2)
B_3<-c(7.6)
B_4<-c(10.3,17.4,19.2)
B_5<-c(3.4,13.5,19.5,18.5,14.6)

```


```{r}
#Estimate from Strata A#
tpmsq <- function(x) {
   result<-length(x)/25
   return(result)
}

tpmsq_A1<-tpmsq(A_1)
tpmsq_A2<-tpmsq(A_2)
tpmsq_A3<-c(0)
tpmsq_A4<-tpmsq(A_4)

tpms_avg<-(tpmsq_A1+tpmsq_A2+tpmsq_A3+tpmsq_A4)/4


est_tpHA_A<-(tpms_avg*10000)*.3
```

```{r}
#Estimate from Strata B#


BAF<-4

tf <- function(x) {
   result<-BAF/((3.14*(x/100)/2)^2)
   return(result)
}

B_trees<-c(18.9,14.5,12.9,14.2,9.9,11.2,21.3,14.2,15.3,8.2,7.6,10.3,17.4,19.2,3.4,13.5,19.5,18.5,14.6)

tf.Btrees<-tf(B_trees)

est.tpHA_B<-(sum(tf.Btrees)/5)*.7

```


```{r}
estimates<-c(est_tpHA_A,est.tpHA_B)

var.est<-var(estimates)


SE<-sqrt(var.est/1)

#90 CI for number of  tpHA#

mean(estimates) + c(-1,1)* SE * qt(p=.80,df=1)

```

(5) 90% CI for baHA

```{r}
#Estimate from Strata A#
A_trees<-c(10.3,10.3,11.2,13.6,11.2,8.5,9.4,6.8,0,9.8,8.9,12.2,5.6,3.4)

bamsq <- function(x) {
   result<-((((x)/100)/2)^2)*3.14
   return(result)
}

bpHA.A<-(sum(bamsq(A_trees))/(4*25))*10000*.3


bpHA.B<-(BAF*length(B_trees)/5)*.7


estimatesBA<-c(bpHA.A,bpHA.B)

var_estBA<-var(estimatesBA)


SE_BA<-sqrt(var_estBA/1)

#90 CI for number of  tpHA#

mean(estimatesBA) + c(-1,1)* SE_BA * qt(p=.80,df=1)

```

(6)
```{r}

```








